language: node_js
node_js:
  - 11

services:
  - docker

before_script:
  - cd ./services/docker/compose
  - docker-compose up --build -d
  - cd ../../../tests
  # - cd ./tests
  - sudo chmod +x test.sh install.sh
  - ./install.sh
  # - npm install -g mocha
  # - npm install chai chai-http chai-arrays

script:
  - ./test.sh
  # - mocha test.js --exit