sudo: required
dist: xenial
addons:
  firefox: latest-esr
      
language: node_js
node_js:
  - 11

before_install:
  - cd './backend'

services:
  - xvfb

before_script:
  - npm install
  - cd './tests'

script:
  - mocha test --exit
