version: '2'
services:
    neural-network:
        build: ../../neural-network/
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            - PORT:5000
